/**
 * ST-41: UI form-state controller for the แกะของ/ย้ายสต็อก page.
 *
 * Pure functions that handle the TransferPage form state transitions.
 * The component calls these; tests call them directly to prove behavior.
 *
 * ST-62 review fix (H-1): the idempotency key lifecycle is owned HERE so it
 * is stable per submission intent. The key is generated by the component
 * (via generateIdempotencyKey) and passed into INIT / SUBMIT_SUCCESS actions,
 * keeping the reducer pure and deterministic for tests.
 *
 * Key invariants:
 *   - INIT: new key K1 set (form mount = new submission intent)
 *   - SET_DATE: key PRESERVED (still composing the same submission)
 *   - SUBMIT_START: key PRESERVED (retry / double-click of same intent)
 *   - SUBMIT_SUCCESS: new key K2 set (intent complete → ready for next)
 *   - SUBMIT_ERROR: key PRESERVED (retry of same intent reuses key)
 */

import {
  getThailandTodayDateString,
  isFutureThailandDate,
  isValidDateString,
  formatThailandBuddhistDate,
} from './thailand-date';

export interface TransferFormState {
  businessDate: string; // YYYY-MM-DD
  submitting: boolean;
  // ST-62: stable per submission intent. Reused across retries/double-click;
  // rotated only on INIT (mount) and SUBMIT_SUCCESS (new intent).
  idempotencyKey: string;
}

export type TransferFormAction =
  | { type: 'INIT'; idempotencyKey: string }
  | { type: 'SET_DATE'; date: string }
  | { type: 'SUBMIT_START' }
  | { type: 'SUBMIT_SUCCESS'; nextIdempotencyKey: string }
  | { type: 'SUBMIT_ERROR' };

/**
 * ST-41: Reducer for the TransferPage form state.
 *
 * Key invariants:
 *   - INIT: businessDate defaults to Thailand today
 *   - SUBMIT_SUCCESS: businessDate resets to Thailand today (ONLY on success)
 *   - SUBMIT_ERROR: businessDate is PRESERVED (not reset)
 *   - submitting: true on SUBMIT_START, false on SUCCESS and ERROR
 *
 * ST-62: idempotencyKey is set on INIT and SUBMIT_SUCCESS, preserved
 * everywhere else (see file header).
 */
export function transferFormReducer(
  state: TransferFormState,
  action: TransferFormAction
): TransferFormState {
  switch (action.type) {
    case 'INIT':
      return { businessDate: getThailandTodayDateString(), submitting: false, idempotencyKey: action.idempotencyKey };
    case 'SET_DATE':
      return { ...state, businessDate: action.date };
    case 'SUBMIT_START':
      return { ...state, submitting: true };
    case 'SUBMIT_SUCCESS':
      // ST-41: reset to today ONLY after successful save.
      // ST-62: rotate to a NEW idempotency key — the next submission is a new intent.
      return { businessDate: getThailandTodayDateString(), submitting: false, idempotencyKey: action.nextIdempotencyKey };
    case 'SUBMIT_ERROR':
      // ST-41: PRESERVE the selected date — do NOT reset on error.
      // ST-62: PRESERVE the idempotency key — a retry of the same submission
      // intent must reuse the key so the server can REPLAY or re-run, not duplicate.
      return { ...state, submitting: false };
    default:
      return state;
  }
}

/**
 * ST-62: Generate a fresh idempotency key for a new submission intent.
 * Called by the component on mount (INIT) and after a successful submit
 * (SUBMIT_SUCCESS). Uses crypto.randomUUID() which is available in modern
 * browsers and in Bun/Node 19+.
 */
export function generateIdempotencyKey(): string {
  return `idem-${Date.now()}-${crypto.randomUUID()}`;
}

/**
 * ST-41: Validate the form before API call.
 * Returns null if valid, or an error message if invalid.
 */
export function validateTransferForm(state: TransferFormState): string | null {
  if (!state.businessDate || state.businessDate.trim() === '') {
    return 'กรุณาระบุวันที่แกะของ';
  }
  if (!isValidDateString(state.businessDate)) {
    return 'รูปแบบวันที่ไม่ถูกต้อง';
  }
  if (isFutureThailandDate(state.businessDate)) {
    return 'ไม่สามารถเลือกวันที่ในอนาคตได้';
  }
  return null;
}

/**
 * ST-41: Build the submit payload date field.
 * Returns YYYY-MM-DD (date-only, not a datetime timestamp).
 */
export function buildSubmitDatePayload(state: TransferFormState): string {
  return state.businessDate;
}
